# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
else
  use_frameworks! :linkage => :static
end

target 'ReactApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix C++ module building for Nitro pods:
    # 1. NitroModules module map needs `requires cplusplus` so its umbrella
    #    header (which includes C++ stdlib headers like <functional>) can be
    #    processed by Clang in C++ mode.
    # 2. NitroEventPipe needs C++ interop mode and C++20 build settings
    #    (the nitrogen autolinking.rb settings aren't being applied).
    installer.pods_project.targets.each do |target|
      if target.name == 'NitroModules'
        support_dir = "#{installer.sandbox.root}/Target Support Files/#{target.name}"
        modulemap_path = "#{support_dir}/#{target.name}.modulemap"
        if File.exist?(modulemap_path)
          content = File.read(modulemap_path)
          unless content.include?('requires cplusplus')
            content.sub!('umbrella header', "requires cplusplus\n  umbrella header")
            File.write(modulemap_path, content)
          end
        end
      end

      if target.name == 'NitroEventPipe'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
          config.build_settings['SWIFT_OBJC_INTEROP_MODE'] = 'objcxx'
          config.build_settings['OTHER_SWIFT_FLAGS'] ||= '$(inherited)'
          config.build_settings['OTHER_SWIFT_FLAGS'] += ' -cxx-interoperability-mode=default'
        end
      end
    end
  end

  target 'RNLib' do
    inherit! :complete
  end
end

